object Dependencies {

  val bm4Version                 = "0.3.1"
  val calibanVersion             = "1.1.0"
  val catsEffectVersion          = "2.5.1"
  val catsTaglessVersion         = "0.14.0"
  val catsVersion                = "2.6.1"
  val chimneyVersion             = "0.6.1"
  val circeVersion               = "0.14.1"
  val derevoVersion              = "0.12.6"
  val doobieVersion              = "0.13.4"
  val enumeratumDoobieVersion    = "1.7.0"
  val enumeratumVersion          = "1.7.0"
  val epimetheusVersion          = "0.4.0"
  val flywayVersion              = "7.11.3"
  val fs2Version                 = "2.5.9"
  val fs2KafkaVersion            = "1.7.0"
  val hikariVersion              = "3.4.3"
  val http4sVersion              = "0.21.25"
  val kindProjectorVersion       = "0.13.0"
  val log4sVersion               = "1.10.0"
  val logbackVersion             = "1.2.4"
  val macroParadiseVersion       = "2.1.1"
  val mouseVersion               = "1.0.4"
  val newtypeVersion             = "0.4.4"
  val prometheusVersion          = "0.11.0"
  val pureconfigVersion          = "0.16.0"
  val refinedVersion             = "0.9.27"
  val scalatestVersion           = "3.2.9"
  val slf4jVersion               = "1.7.32"
  val testcontainersJavaVersion  = "1.16.0"
  val testcontainersScalaVersion = "0.39.5"
  val tofuVersion                = "0.10.3"
  val trace4catsVersion          = "0.11.0"
  val zioVersion                 = "1.0.9"
  val zioInteropCatsVersion      = "2.5.1.0"

}
